apiVersion: batch/v1
kind: Job
metadata:
  name: nodebase-staging-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: 916785371700.dkr.ecr.us-east-1.amazonaws.com/nodebase:REPLACE_WITH_GIT_SHA
          workingDir: /app
          command: ["./node_modules/.bin/prisma"]
          args: ["migrate", "deploy"]
          envFrom:
            - secretRef:
                name: nodebase-staging-secret
          volumeMounts:
            - name: secret
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: nodebase-staging-secret
            items:
              - key: .env
                path: .env
