# Replace via ./scripts/seal-secret.sh staging
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nodebase-staging-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .env: REPLACE_ME_RUN_scripts/seal-secret.sh
  template:
    metadata:
      name: nodebase-staging-secret
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
