apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nodebase-cert
  namespace: default
spec:
  secretName: nodebase-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nodebase.aws.ishankdev.me
